# Main navigation.
nav:
  - Einleitung:
      - PhotoPrism: index.md
  - Handbuch:
      - Einleitung: user-guide/index.md
      # - Setting up: user-guide/setup.md
      - Navigation: user-guide/navigate.md
      - Dateien hinzufügen:
          - Einleitung: user-guide/library/import-vs-index.md
          - Indexieren: user-guide/library/indexing.md
          - Importieren: user-guide/library/import.md
          - Upload über die App: user-guide/library/upload.md
          - WebDAV Upload: user-guide/library/webdav.md
          - Originale: user-guide/library/files.md
        #- Import from camera: user-guide.md
        #- Import from Facebook: user-guide.md
        #- Import from NAS: user-guide.md
        #- Import from Apple Photos: user-guide.md
        #- Import from One Drive: user-guide.md
      # - Sync and Back Up:
      # - WebDAV Sync
      #    - Nextcloud: user-guide/nextcloud.md
      - Organisation:
          - Übersicht:
            - Bereiche: user-guide/organize/browse.md
            - Ansichten: user-guide/organize/views.md
          - Suche & Filter: user-guide/organize/search.md
          - Überprüfen: user-guide/organize/review.md
          - Bildstapel: user-guide/organize/stacks.md
          - Panoramas: user-guide/organize/panoramas.md
          - Scans: user-guide/organize/scans.md
          - Privat: user-guide/organize/private.md
          - Archiv: user-guide/organize/archive.md
          - Alben: user-guide/organize/albums.md
          - Ordner: user-guide/organize/folders.md
          - Kategorien: user-guide/organize/labels.md
          - Karten: user-guide/organize/places.md
          - Videos: user-guide/organize/video.md
          - Erlebnisse: user-guide/organize/moments.md
          - Kalender: user-guide/organize/calendar.md
          - Fotos herunterladen: user-guide/organize/download.md
          - Fotos bearbeiten: user-guide/organize/edit.md
          - Fotos löschen: user-guide/organize/delete.md
      - Sync & Backup:
          - Verbindung via WebDAV:  user-guide/sync/webdav.md
          - Backup von Smartphones:  user-guide/sync/sync-phone.md
      - Teilen:
          - Album über Link teilen: user-guide/share/share.md
      - Einstellungen:
          - Allgemein: user-guide/settings/general.md
          - Dateien: user-guide/settings/library.md
          - Erweitert: user-guide/settings/advanced.md
          - Sync:  user-guide/settings/sync.md
          - Konto: user-guide/settings/account.md
          #- Places: user-guide/settings/places.md
      - Migrieren:
          - Von Google Photos wechseln: user-guide/use-cases/google.md
          - Von Apple Photos wechseln: user-guide/use-cases/apple.md
          - Von Flickr wechseln: user-guide/use-cases/flickr.md
          #- Link directories from remote:
      - Weiteres:
          - Metadaten: user-guide/advanced/metadata.md
          - Backups: user-guide/advanced/backups.md
          - Verzeichnisse: user-guide/advanced/folders.md
      - FAQ: user-guide/faq.md
    # - Metadata: user-guide/metadata.md

# External links.
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/photoprism
    - icon: fontawesome/brands/paypal
      link: https://www.paypal.me/photoprism
    - icon: material/chat
      link: https://gitter.im/browseyourlife/community
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/photoprism_app
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/photoprism/
    - icon: material/home
      link: https://photoprism.org/

# Project paths.
docs_dir: docs
site_dir: site

# Project information.
site_name: PhotoPrism
site_description: User Guide - German
site_author: PhotoPrism.org
site_url: https://docs.photoprism.org/de

# Repository information.
repo_name: photoprism/photoprism
repo_url: https://github.com/photoprism/photoprism
edit_uri: ""
copyright: 'Made with ❤ in Berlin'

# Theme configuration.
theme:
  name: 'material'
  custom_dir: overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: de
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: white
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: img/favicon-16.png

plugins:
  - search

# MkDocs extensions.
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
