# Main navigation.
nav:
  - Funktionen: index.md
  - Erste Schritte: user-guide/index.md
  # - Setting up: user-guide/setup.md
  - Deine Dateien:
      - Einleitung: user-guide/library/import-vs-index.md
      - Originale indexieren: user-guide/library/indexing.md
      - Dateien importieren: user-guide/library/import.md
      - Doppelte Dateien: user-guide/library/duplicates.md
      - Bild Metadaten: user-guide/advanced/metadata.md
      - Web Datei Upload: user-guide/library/upload.md
      - WebDAV Datei Sync: user-guide/library/webdav.md
      - Datei Browser: user-guide/library/files.md
    #- Import from camera: user-guide.md
    #- Import from Facebook: user-guide.md
    #- Import from NAS: user-guide.md
    #- Import from Apple Photos: user-guide.md
    #- Import from One Drive: user-guide.md
  # - Sync and Back Up:
  # - WebDAV Sync
  #    - Nextcloud: user-guide/nextcloud.md
  - Bilder entdecken:
      - Benutzeroberfläche: user-guide/navigate.md
      - Funktionen & Bereiche: user-guide/organize/browse.md
      - Ansichten: user-guide/organize/views.md
      - Suchfilter verwenden: user-guide/organize/search.md
  - Bilder organisieren:
      - Alben: user-guide/organize/albums.md
      - Personen: user-guide/organize/people.md
      - Kategorien: user-guide/organize/labels.md
      - Archiv: user-guide/organize/archive.md
      - Bilder löschen: user-guide/organize/delete.md
      - Privat: user-guide/organize/private.md
      - Überprüfen: user-guide/organize/review.md
      - Bildstapel: user-guide/organize/stacks.md
      - Metadaten bearbeiten: user-guide/organize/edit.md
      - Bilder herunterladen: user-guide/organize/download.md
      - Videos: user-guide/organize/video.md
      - Orte: user-guide/organize/places.md
      - Erlebnisse: user-guide/organize/moments.md
      - Kalender: user-guide/organize/calendar.md
      - Ordner: user-guide/organize/folders.md
      - Panoramas: user-guide/organize/panoramas.md
      - Scans: user-guide/organize/scans.md
  - Linkfreigabe:
      - Alben: user-guide/share/share.md
  - Fern-Synchronisation:
      - WebDAV Verbindung:  user-guide/sync/webdav.md
      - Smartphones:  user-guide/sync/sync-phone.md
  - Einstellungen:
      - Allgemein: user-guide/settings/general.md
      - Dateien: user-guide/settings/library.md
      - Erweitert: user-guide/settings/advanced.md
      - Sync:  user-guide/settings/sync.md
      - Konto: user-guide/settings/account.md
      #- Places: user-guide/settings/places.md
  - Backup Anleitung:
      - Backups erstellen: user-guide/advanced/backups.md
      - Backups wiederherstellen: user-guide/advanced/restore.md
      - Metadaten Export: user-guide/advanced/export.md
      - Verzeichnis Übersicht: user-guide/advanced/folders.md
  - Cloud Migration:
      - Google Photos: user-guide/use-cases/google.md
      - Apple Photos: user-guide/use-cases/apple.md
      - Flickr: user-guide/use-cases/flickr.md
      #- Link directories from remote:
  - Mobile App (PWA): user-guide/pwa.md
  - FAQ: user-guide/faq.md
  # - Metadata: user-guide/metadata.md

extra_css:
  - css/custom.css

# External links.
extra:
  generator: false
  homepage: https://photoprism.app
  alternate:
    - name: 🇬🇧 English
      link: https://docs.photoprism.app/
      lang: en
    - name: 🇩🇪 Deutsch
      link: /
      lang: de
  social:
    - icon: fontawesome/brands/github
      link: https://link.photoprism.app/github
    - icon: fontawesome/brands/patreon
      link: https://link.photoprism.app/patreon
    - icon: material/chat
      link: https://link.photoprism.app/chat
    - icon: fontawesome/brands/twitter
      link: https://link.photoprism.app/twitter
    - icon: fontawesome/brands/reddit
      link: https://link.photoprism.app/reddit
    - icon: fontawesome/brands/linkedin
      link: https://link.photoprism.app/linkedin
    - icon: material/home
      link: https://photoprism.app/

# Project paths.
docs_dir: docs
site_dir: site

# Project information.
site_name: PhotoPrism
site_description: Dokumentation
site_author: PhotoPrism UG
site_url: https://docs-de.photoprism.app/

# Repository information.
repo_name: photoprism/photoprism
repo_url: https://github.com/photoprism/photoprism
edit_uri: https://github.com/photoprism/photoprism-docs-de/tree/master/docs
copyright: 'Made with ❤ in Berlin'

# Theme configuration.
theme:
  name: 'material'
  custom_dir: overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: de
  features:
    - navigation.top
  palette:
    scheme: default
    primary: white
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  favicon: icons/favicon.ico
  icon:
    logo: logo

plugins:
  - search

# MkDocs extensions.
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - md_in_html
  - attr_list
  - tables
  - abbr
  - meta